.gitignore, src/main/java/tf/tailfriend/admin/controller/AdminController.java, src/main/java/tf/tailfriend/admin/dto/AdminLoginRequest.java, src/main/java/tf/tailfriend/admin/dto/AdminLoginResponse.java, src/main/java/tf/tailfriend/admin/repository/AdminDao.java, src/main/java/tf/tailfriend/admin/service/AdminService.java, src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/resources/application.properties, src/main/resources/application.yml
- Admin쪽 로그인 1차 구현
- application.yml 수정
- gitignore application-local.yml 추가
- application.properties -> application.yml 변경
- application.yml
- jpa 추가
- datasource 추가
- hikaripool 추가
Closes #
=> [ADD] admin 로그인 1차구현/application.yml 수정

src/main/java/tf/tailfriend/global/config/OAuth2SuccessHandler.java, src/main/java/tf/tailfriend/global/config/SecurityConfig.java
=> [MODIFY] 클라우드 관련 시큐리티 설정

.dockerignore, Dockerfile, deployment.yaml, src/main/resources/application.yml
=> [ADD]k8s, jenkins 연동

src/main/java/tf/tailfriend/admin/controller/AdminBoardController.java, src/main/java/tf/tailfriend/admin/controller/AdminController.java, src/main/java/tf/tailfriend/admin/exception/AdminException.java, src/main/java/tf/tailfriend/admin/service/AdminService.java, src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java, src/main/java/tf/tailfriend/board/repository/BoardDao.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/global/config/SecurityConfig.java
- 게시글 관리 1차 구현
-
-
-
-
- #17 
Closes #17
=> [FEAT] 게시글 관리 1차 구현

src/main/resources/application.yml
=> [FIX] 환경변수 설정

src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/resources/application.yml
=> [fix] API 호출경로 변경

src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/resources/application.yml
=> [MODIFY] 시큐리티 관련 디버깅 코드 추가

src/main/java/tf/tailfriend/global/config/CookieUtils.java, src/main/java/tf/tailfriend/global/config/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/tf/tailfriend/global/config/SecurityConfig.java
=> [MODIFY] 쿠키관련 설정 추가

src/main/java/tf/tailfriend/global/config/SecurityConfig.java
=> [MODIFY] 시큐리티 수정

build.gradle, src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java, src/main/java/tf/tailfriend/file/entity/File.java, src/main/java/tf/tailfriend/file/repository/FileDao.java, src/main/java/tf/tailfriend/file/repository/FileRepository.java, src/main/java/tf/tailfriend/file/service/FileService.java, src/main/java/tf/tailfriend/global/service/NCPObjectStorageService.java, src/main/java/tf/tailfriend/global/service/StorageService.java, src/main/java/tf/tailfriend/global/service/StorageServiceException.java, src/main/java/tf/tailfriend/petsta/controller/PetstaController.java, src/main/java/tf/tailfriend/petsta/controller/PetstaPostController.java, src/main/java/tf/tailfriend/petsta/entity/PetstaPost.java, src/main/java/tf/tailfriend/petsta/repository/PetstaPostDao.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java, src/main/java/tf/tailfriend/user/repository/SnsTypeDao.java, src/main/java/tf/tailfriend/user/repository/UserDao.java, src/main/java/tf/tailfriend/user/service/AuthService.java, src/main/java/tf/tailfriend/user/service/UserService.java, src/main/resources/application.yml
=> [ADD]서버에 게시물 업로드 구현

src/main/java/tf/tailfriend/global/config/CookieUtils.java, src/main/java/tf/tailfriend/global/config/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/tf/tailfriend/global/config/OAuth2SuccessHandler.java, src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/java/tf/tailfriend/user/controller/AuthController.java, src/main/java/tf/tailfriend/user/service/UserService.java, src/main/resources/application.yml
=> [MODIFY] CookiUtils 사용, 쿠키생성 분기처리

deployment.yaml
=> [FIX]deployment 수정

src/main/java/tf/tailfriend/admin/controller/AdminAnnounceController.java, src/main/java/tf/tailfriend/admin/controller/AdminController.java, src/main/java/tf/tailfriend/admin/dto/AnnounceResponseDto.java, src/main/java/tf/tailfriend/admin/entity/Announce.java, src/main/java/tf/tailfriend/admin/exception/ExistEmailException.java, src/main/java/tf/tailfriend/admin/message/error/ErrorMessage.java, src/main/java/tf/tailfriend/admin/repository/AnnounceDao.java, src/main/java/tf/tailfriend/admin/service/AdminService.java, src/main/java/tf/tailfriend/admin/service/AnnounceService.java, src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java, src/main/java/tf/tailfriend/board/entity/Board.java, src/main/java/tf/tailfriend/board/entity/BoardLike.java, src/main/java/tf/tailfriend/board/repository/BoardTypeDao.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/board/service/BoardTypeService.java, src/main/java/tf/tailfriend/board/service/CommentService.java, src/main/java/tf/tailfriend/file/service/FileService.java, src/main/java/tf/tailfriend/global/config/JwtAuthenticationFilter.java, src/main/java/tf/tailfriend/global/config/JwtTokenProvider.java, src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/java/tf/tailfriend/petsta/entity/PetstaLike.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java, src/main/java/tf/tailfriend/user/service/UserService.java, src/main/resources/application.yml
=> [FEAT] 공지 작성 1차

Dockerfile, src/main/java/tf/tailfriend/board/entity/BoardBookmark.java, src/main/java/tf/tailfriend/board/entity/BoardLike.java, src/main/java/tf/tailfriend/file/service/FileService.java, src/main/java/tf/tailfriend/petsta/controller/PetstaPostController.java, src/main/java/tf/tailfriend/petsta/entity/PetstaLike.java, src/main/java/tf/tailfriend/petsta/entity/PetstaPost.java, src/main/java/tf/tailfriend/petsta/entity/dto/PostResponseDto.java, src/main/java/tf/tailfriend/petsta/repository/PetstaBookmarkDao.java, src/main/java/tf/tailfriend/petsta/repository/PetstaLikeDao.java, src/main/java/tf/tailfriend/petsta/repository/PetstaPostDao.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java
=> [ADD]동영상 업로드 구현

src/main/java/tf/tailfriend/admin/controller/AdminAnnounceController.java, src/main/java/tf/tailfriend/admin/service/AnnounceService.java, src/main/java/tf/tailfriend/board/entity/BoardBookmark.java, src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/facility/entity/FacilityTimetable.java, src/main/java/tf/tailfriend/file/service/FileService.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java, src/main/java/tf/tailfriend/user/entity/dto/PetPhotoDto.java, src/main/java/tf/tailfriend/user/service/UserService.java
공지 작성 2차
- NCP Object Storage 연결
- 확장자 추가
-
-
-
- #43 
Closes #43
=> [FEAT] 공지 작성 2차

src/main/java/tf/tailfriend/user/controller/AuthController.java, src/main/java/tf/tailfriend/user/entity/dto/RegisterPetDto.java, src/main/java/tf/tailfriend/user/entity/dto/RegisterPetPhotoDto.java, src/main/java/tf/tailfriend/user/entity/dto/RegisterUserDto.java, src/main/java/tf/tailfriend/user/service/UserService.java
=> [MODIFY] 회원가입  사진 Object Storage에 업로드 - 1차

src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/petsitter/dto/PetSitterResponseDto.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
- 펫시터/게시판 목록 썸네일 표시
-
-
object storage에 없어서 깨져보임
- #50 
Closes #50
=> [FEAT] 펫시터/게시판 목록 썸네일 표시

src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java, src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/petsitter/dto/PetSitterResponseDto.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
펫시터 목록 상세보기 구현
-
-
-
- #54 
Closes #54
=> [FEAT] 펫시터 목록 상세보기

src/main/java/tf/tailfriend/pet/controller/PetController.java, src/main/java/tf/tailfriend/pet/entity/Pet.java, src/main/java/tf/tailfriend/pet/entity/dto/PetDetailResponseDto.java, src/main/java/tf/tailfriend/pet/entity/dto/PetRequestDto.java, src/main/java/tf/tailfriend/pet/repository/PetTypeDao.java, src/main/java/tf/tailfriend/pet/service/PetService.java, src/main/java/tf/tailfriend/user/controller/MemberController.java, src/main/java/tf/tailfriend/user/repository/UserDao.java, src/main/java/tf/tailfriend/user/service/MemberService.java
=> [FEAT]마이페이지 조회/수정/삭제/추가

src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java, src/main/java/tf/tailfriend/petsitter/repository/PetSitterDao.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
펫시터 리스트에 applyAt 조건 추가
- applyAt 컬럼이 nul이 아니어야 보이게끔 수정
-
-
-
- #60 
Closes #60
=> [FEAT] 펫시터리스트 applyAt 조건 추가

src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java
펫시터 신청목록 구현
-
-
- applyAt이 null인 펫시터만 전송
- #64 
Closes #64
=> [FEAT] 펫시터 신청목록 구현

src/main/java/tf/tailfriend/petsta/controller/PetstaPostController.java, src/main/java/tf/tailfriend/petsta/entity/PetstaComment.java, src/main/java/tf/tailfriend/petsta/entity/dto/CommentRequestDto.java, src/main/java/tf/tailfriend/petsta/entity/dto/CommentResponseDto.java, src/main/java/tf/tailfriend/petsta/repository/PetstaCommentDao.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java
=> [ADD]댓글 기능 구현

src/main/java/tf/tailfriend/global/config/OAuth2SuccessHandler.java, src/main/java/tf/tailfriend/user/repository/UserDao.java, src/main/java/tf/tailfriend/user/service/AuthService.java
=> [FIX] 회원가입 불가현상 수정, 이메일/sns타입으로 회원가입여부 검증

src/main/java/tf/tailfriend/user/repository/UserDao.java, src/main/java/tf/tailfriend/user/service/AuthService.java
=> [FIX] 회원가입여부 확인 메서드 optional로 변경

src/main/java/tf/tailfriend/user/service/UserService.java
=> [MODIFY] UserService 관련내용 삭제

src/main/java/tf/tailfriend/user/controller/AuthController.java, src/main/java/tf/tailfriend/user/entity/dto/UserInfoDto.java, src/main/java/tf/tailfriend/user/service/AuthService.java
=> [FIX]로그인 과정 수정

src/main/java/tf/tailfriend/user/controller/AuthController.java
=> [FIX] 예외처리 제거

src/main/java/tf/tailfriend/user/service/AuthService.java
=> [FIX] 펫사진 저장경로 변경

src/main/java/tf/tailfriend/schedule/controller/ScheduleController.java, src/main/java/tf/tailfriend/schedule/entity/dto/ScheduleDTO.java, src/main/java/tf/tailfriend/schedule/repository/ScheduleDao.java, src/main/java/tf/tailfriend/schedule/service/ScheduleService.java
=> [FEAT] 캘린더 스케쥴 GET 메서드 생성

src/main/java/tf/tailfriend/admin/controller/AdminBoardController.java, src/main/java/tf/tailfriend/admin/controller/AdminFacilityController.java, src/main/java/tf/tailfriend/admin/controller/AdminPetSitterController.java, src/main/java/tf/tailfriend/board/repository/BoardDao.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/facility/dto/FacilityResponseDto.java, src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/facility/repository/FacilityDao.java, src/main/java/tf/tailfriend/facility/repository/FacilityTypeDao.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java, src/main/java/tf/tailfriend/petsitter/repository/PetSitterDao.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
관리자 페이지 전체적으로 수정
-검색/필터 분리
-
-
-
- #84 
Closes #84
=> [FIX] 관리자 페이지 전체적으로 수정

build.gradle, src/main/java/tf/tailfriend/global/service/NCPObjectStorageService.java, src/main/java/tf/tailfriend/global/service/RedisService.java, src/main/java/tf/tailfriend/petsta/controller/PetstaController.java, src/main/java/tf/tailfriend/petsta/controller/PetstaPostController.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaCommentResponseDto.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaFollowingUserDto.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaPostResponseDto.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaUserpageResponseDto.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java, src/main/java/tf/tailfriend/petsta/service/PetstaService.java, src/main/java/tf/tailfriend/user/repository/UserFollowDao.java, src/main/resources/application.yml
=> [ADD]스토리상태 구현

src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java, src/main/java/tf/tailfriend/petsitter/entity/PetSitter.java, src/main/java/tf/tailfriend/petsitter/repository/PetSitterDao.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java, src/main/java/tf/tailfriend/user/controller/UserController.java
=> [MODIFY] 마이페이지 펫시터 수정

src/main/java/tf/tailfriend/pet/controller/PetController.java, src/main/java/tf/tailfriend/pet/exception/GetMyPetException.java, src/main/java/tf/tailfriend/pet/repository/PetDao.java, src/main/java/tf/tailfriend/pet/service/PetService.java, src/main/resources/application.yml
친구 불러오기 쿼리 반려동물 주인 != 본인  조건 추가
Closes #108
=> [FIX] 친구 불러오기 본인 반려동물 제외

build.gradle, src/main/java/tf/tailfriend/admin/controller/AdminBoardController.java, src/main/java/tf/tailfriend/admin/controller/AdminFacilityController.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/facility/dto/FacilityAddResponseDto.java, src/main/java/tf/tailfriend/facility/dto/FacilityRequestDto.java, src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/facility/repository/FacilityPhotoDao.java, src/main/java/tf/tailfriend/facility/repository/FacilityTimetableDao.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java, src/main/resources/application.yml
업체 등록 페이지 1차
-
-
-
- #104 
Closes #104
=> [FEAT] 업체 등록 페이지 1차

src/main/java/tf/tailfriend/chat/controller/ChatController.java, src/main/java/tf/tailfriend/chat/entity/ChatRoom.java, src/main/java/tf/tailfriend/chat/entity/dto/ChatRoomResponseDto.java, src/main/java/tf/tailfriend/chat/repository/ChatDao.java, src/main/java/tf/tailfriend/chat/repository/ChatRoomDao.java, src/main/java/tf/tailfriend/chat/service/ChatService.java, src/main/java/tf/tailfriend/petsta/controller/PetstaController.java, src/main/java/tf/tailfriend/petsta/controller/PetstaPostController.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java, src/main/java/tf/tailfriend/petsta/service/PetstaService.java, src/main/java/tf/tailfriend/user/repository/UserFollowDao.java, src/main/resources/application.yml
=> [ADD]채팅 기능 구현

src/main/java/tf/tailfriend/file/controller/FileController.java, src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java, src/main/java/tf/tailfriend/petsitter/entity/PetSitter.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java, src/main/java/tf/tailfriend/user/controller/UserController.java
- 유저 프로필 이미지를 수정할 수 있다
Closes #15
=> [ADD] 유저 프로필 이미지 수정

build.gradle, src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/java/tf/tailfriend/global/config/UserPrincipal.java, src/main/java/tf/tailfriend/notification/config/NotificationReceiver.java, src/main/java/tf/tailfriend/notification/config/NotificationSender.java, src/main/java/tf/tailfriend/notification/config/RabbitConfig.java, src/main/java/tf/tailfriend/notification/config/WebSocketConfig.java, src/main/java/tf/tailfriend/notification/controller/NotificationController.java, src/main/java/tf/tailfriend/notification/entity/dto/NotificationDto.java, src/main/java/tf/tailfriend/notification/repository/NotificationTypeDao.java, src/main/java/tf/tailfriend/notification/service/NotificationService.java, src/main/java/tf/tailfriend/user/controller/AuthController.java, src/main/resources/application.yml
-> postman이나 기타 안되는거 있으면
SecurityConfig 수정하기
=> [FEAT] rabbitmq 알람 테스트, CSRF 활성화, 개발 프록시 우회

src/main/java/tf/tailfriend/admin/controller/AdminFacilityController.java, src/main/java/tf/tailfriend/facility/dto/FacilityRequestDto.java, src/main/java/tf/tailfriend/facility/entity/FacilityTimetable.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java
업체 등록 구현
- 업체 등록 안되는 문제 수정
- FacilityTimetable.java ENUM값 수정
```java
@Getter
public enum Day {
MON("MON"),
TUE("TUE"),
WED("WED"),
THU("THU"),
FRI("FRI"),
SAT("SAT"),
SUN("SUN");
private final String value;
Day(String value) {
this.value = value;
}
}
```
-
-
-
- #115 
Closes #115
=> [FIX] 업체등록 페이지 2차

build.gradle, src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/java/tf/tailfriend/schedule/service/ScheduleService.java
=> [MODIFY] 클라우드 설정 용 테스트

src/main/java/tf/tailfriend/admin/service/AnnounceService.java, src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java, src/main/java/tf/tailfriend/petsitter/entity/PetSitter.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java, src/main/java/tf/tailfriend/user/controller/UserController.java
-  트랜잭션 격리 수준을 READ_UNCOMMITTED로 낮춤
- User 엔티티가 detached 상태
Closes #87
=> [Modify]3차 마이페이지 펫시터 신청

src/main/java/tf/tailfriend/global/config/SecurityConfig.java
관리자쪽 csrf 비활성화
- 관리자쪽 api 들은 csrf 비활성화
-
-
-
-
=> [FIX] 관리자 csrf 비활성화

src/main/java/tf/tailfriend/chat/controller/ChatController.java, src/main/java/tf/tailfriend/chat/entity/dto/ChatRoomListResponseDto.java, src/main/java/tf/tailfriend/chat/entity/dto/ChatRoomResponseDto.java, src/main/java/tf/tailfriend/chat/repository/ChatRoomDao.java, src/main/java/tf/tailfriend/chat/service/ChatService.java, src/main/java/tf/tailfriend/pet/entity/PetMatch.java, src/main/java/tf/tailfriend/pet/entity/dto/PetDetailResponseDto.java, src/main/java/tf/tailfriend/pet/repository/PetMatchDao.java, src/main/java/tf/tailfriend/pet/service/PetService.java
=> [ADD]매칭 기능 구현

src/main/java/tf/tailfriend/admin/controller/AdminBoardController.java, src/main/java/tf/tailfriend/admin/controller/AdminFacilityController.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
DeleteMapping으로 수정
펫시터 상세보기 이미지 경로 수정
-
-
-
-
-
=> [FIX] deletemapping으로 수정

src/main/java/tf/tailfriend/board/dto/BoardBookmarkResponseDto.java, src/main/java/tf/tailfriend/board/entity/Board.java, src/main/java/tf/tailfriend/board/repository/BoardBookmarkDao.java, src/main/java/tf/tailfriend/bookmark/controller/BookmarkController.java, src/main/java/tf/tailfriend/bookmark/service/BookmarkService.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaBookmarkResponseDto.java, src/main/java/tf/tailfriend/petsta/repository/PetstaBookmarkDao.java, src/main/java/tf/tailfriend/user/controller/AuthController.java
- 사용자별 북마크 목록 조회
- 펫스타 및 게시글 북마크 분리 및 통합 조회
- 게시판 타입별 북마크 조회
Closes #131
=> [FEAT]북마크 기능 구현

src/main/java/tf/tailfriend/board/controller/BoardController.java, src/main/java/tf/tailfriend/board/dto/BoardRequestDto.java, src/main/java/tf/tailfriend/board/dto/BoardResponseDto.java, src/main/java/tf/tailfriend/board/entity/Board.java, src/main/java/tf/tailfriend/board/entity/BoardPhoto.java, src/main/java/tf/tailfriend/board/entity/Product.java, src/main/java/tf/tailfriend/board/repository/BoardBookmarkDao.java, src/main/java/tf/tailfriend/board/repository/BoardLikeDao.java, src/main/java/tf/tailfriend/board/repository/CommentDao.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/board/service/CommentService.java
=> [FEAT] 게시글 추가 삭제 수정

src/main/java/tf/tailfriend/pet/entity/Pet.java, src/main/java/tf/tailfriend/pet/entity/PetPhoto.java, src/main/java/tf/tailfriend/pet/entity/dto/PetRequestDto.java, src/main/java/tf/tailfriend/pet/service/PetService.java
- PetService.java에서 mainPhotoIndex 처리하도록 추가 (썸네일)
- PetPhoto에 setter나 update 메서드 추가
Closes #15
=> [MODIFY]마이페이지쪽 반려동물 추가/수정 이미지

src/main/java/tf/tailfriend/board/entity/Board.java, src/main/java/tf/tailfriend/board/repository/BoardBookmarkDao.java
=> [FIX] Dao 누락된 코드 추가

src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/java/tf/tailfriend/petsta/controller/PetstaPostController.java, src/main/java/tf/tailfriend/petsta/entity/PetstaComment.java, src/main/java/tf/tailfriend/petsta/entity/PetstaCommentMention.java, src/main/java/tf/tailfriend/petsta/entity/PetstaPost.java, src/main/java/tf/tailfriend/petsta/entity/dto/MentionDto.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaCommentRequestDto.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaCommentResponseDto.java, src/main/java/tf/tailfriend/petsta/entity/dto/PostUpdateDto.java, src/main/java/tf/tailfriend/petsta/exception/PostNotFoundException.java, src/main/java/tf/tailfriend/petsta/repository/PetstaPostDao.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java
=> [ADD]댓글 삭제 기능 추가

src/main/java/tf/tailfriend/board/entity/Board.java
=> [FIX] merge중 생긴 코드 누락 수정

src/main/java/tf/tailfriend/petsta/controller/PetstaPostController.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java
=> [FIX]댓글 수정

src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java
=> [FIX] 클라우드 실행

src/main/java/tf/tailfriend/chat/controller/ChatController.java, src/main/java/tf/tailfriend/chat/entity/TradeMatch.java, src/main/java/tf/tailfriend/chat/repository/TradeMatchDao.java, src/main/java/tf/tailfriend/chat/service/ChatService.java, src/main/java/tf/tailfriend/petsta/repository/PetstaPostDao.java, src/main/java/tf/tailfriend/petsta/service/PetstaService.java
=> [ADD]중고거래 채팅 구현

src/main/java/tf/tailfriend/notification/service/NotificationService.java
=> [fix] 환경변수 연동, 클라우드에서 이미지 띄우기 

src/main/java/tf/tailfriend/admin/controller/AdminFacilityController.java, src/main/java/tf/tailfriend/board/repository/CommentDao.java, src/main/java/tf/tailfriend/board/service/BoardService.java, src/main/java/tf/tailfriend/chat/repository/TradeMatchDao.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java
관리자 업체 등록 이미지 수정 3차
관리자 업체 기존 이미지 보존
-
-
-
- #155 
Closes #155
=> [FIX] 관리자 업체 등록 이미지 수정 3차

src/main/java/tf/tailfriend/board/controller/BoardController.java, src/main/java/tf/tailfriend/board/repository/CommentDao.java, src/main/java/tf/tailfriend/notification/config/RabbitConfig.java, src/main/java/tf/tailfriend/notification/controller/NotificationController.java, src/main/java/tf/tailfriend/notification/entity/Notification.java, src/main/java/tf/tailfriend/notification/entity/dto/GetNotifyDto.java, src/main/java/tf/tailfriend/notification/repository/NotificationDao.java, src/main/java/tf/tailfriend/notification/service/NotificationService.java, src/main/java/tf/tailfriend/petsta/repository/PetstaCommentDao.java, src/main/resources/application.yml
=> [FIX] 알람 진짜 정상화

src/main/java/tf/tailfriend/pet/controller/PetController.java, src/main/java/tf/tailfriend/pet/entity/Pet.java, src/main/java/tf/tailfriend/pet/service/PetService.java
-  이미지 변경사항 적용
- 몸무게 (number -> text)
- 이미지 슬라이드 변경
- 생일 현재시까지만 가능
Closes #15
=> [FIX] 반려동물 수정

src/main/java/tf/tailfriend/Application.java, src/main/java/tf/tailfriend/petsta/entity/dto/PetstaPostResponseDto.java
=> [FIX]출력되는 시간 수정

src/main/java/tf/tailfriend/chat/entity/ChatRoom.java, src/main/java/tf/tailfriend/chat/repository/ChatRoomDao.java, src/main/java/tf/tailfriend/notification/config/NotificationMessageConsumer.java, src/main/java/tf/tailfriend/notification/config/RabbitConfig.java, src/main/java/tf/tailfriend/notification/controller/NotificationController.java, src/main/java/tf/tailfriend/notification/entity/dto/ChatNotificationDto.java, src/main/java/tf/tailfriend/notification/scheduler/NotificationScheduler.java, src/main/java/tf/tailfriend/notification/service/NotificationService.java
=> [FEAT] 채팅알림 구현

src/main/resources/application.yml
=> [FIX]업로드 최대 용량 수정

src/main/java/tf/tailfriend/notification/config/NotificationMessageConsumer.java, src/main/java/tf/tailfriend/notification/config/RabbitConfig.java, src/main/java/tf/tailfriend/notification/entity/Notification.java, src/main/java/tf/tailfriend/notification/repository/NotificationDao.java, src/main/java/tf/tailfriend/notification/service/NotificationService.java
=> [MODIFY] 채팅알림 기능개선

src/main/java/tf/tailfriend/global/config/OAuth2SuccessHandler.java, src/main/java/tf/tailfriend/global/config/SecurityConfig.java, src/main/java/tf/tailfriend/petsta/repository/PetstaCommentDao.java, src/main/java/tf/tailfriend/petsta/repository/PetstaPostDao.java, src/main/java/tf/tailfriend/user/controller/AuthController.java, src/main/java/tf/tailfriend/user/service/UserService.java, src/main/resources/application.yml
=> [MODIFY] 회원탈퇴 의존성 삭제 추가

src/main/java/tf/tailfriend/admin/service/AnnounceService.java, src/main/java/tf/tailfriend/notification/config/NotificationMessageConsumer.java, src/main/java/tf/tailfriend/notification/config/NotificationMessageProducer.java, src/main/java/tf/tailfriend/notification/controller/UserFcmController.java, src/main/java/tf/tailfriend/notification/entity/UserFcm.java, src/main/java/tf/tailfriend/notification/entity/dto/NotificationDto.java, src/main/java/tf/tailfriend/notification/entity/dto/UserFcmDto.java, src/main/java/tf/tailfriend/notification/repository/UserFcmDao.java, src/main/java/tf/tailfriend/notification/scheduler/NotificationScheduler.java, src/main/java/tf/tailfriend/notification/service/FirebaseService.java, src/main/java/tf/tailfriend/notification/service/NotificationService.java, src/main/java/tf/tailfriend/notification/service/UserFcmService.java
=> [MODIFY] 알람토큰DB수정

src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java, src/main/java/tf/tailfriend/petsitter/dto/PetSitterRequestDto.java, src/main/java/tf/tailfriend/petsitter/dto/PetSitterResponseDto.java, src/main/java/tf/tailfriend/petsitter/entity/PetSitter.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
-  DB에 pet_types_formatted 컬럼 추가
- PetSitter 엔티티 클래스에 petTypesFormatted 필드 추가
- DTO 클래스들(Request/Response)에 다중 반려동물 타입 관련 필드 추가
- PetSitterService에서 다중 반려동물 타입 처리 로직 구현
Closes #63
=> [MODIFY] 펫시터 다중 반려동물 타입 기능 수정

src/main/java/tf/tailfriend/global/config/RestTemplateConfig.java, src/main/java/tf/tailfriend/global/service/RedisService.java, src/main/java/tf/tailfriend/reserve/controller/ReserveController.java, src/main/java/tf/tailfriend/reserve/dto/ReserveRequestDto.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java, src/main/resources/application.yml
=> [ADD]결제하기 구현

src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/facility/repository/ReviewDao.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java, src/main/java/tf/tailfriend/reserve/controller/ReserveController.java, src/main/java/tf/tailfriend/reserve/dto/RequestForFacility/ReviewInsertRequestDto.java
=> [FEAT]리뷰 쓰기 백엔드 1차(사진 업로드 미구현)

src/main/java/tf/tailfriend/reserve/controller/ReserveController.java, src/main/java/tf/tailfriend/reserve/dto/ReserveListResponseDto.java, src/main/java/tf/tailfriend/reserve/repository/ReserveDao.java, src/main/java/tf/tailfriend/reserve/service/PaymentService.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java
=> [ADD]내 예약 목록 구현

src/main/java/tf/tailfriend/facility/controller/FacilityController.java, src/main/java/tf/tailfriend/facility/dto/ReviewResponseDto.java, src/main/java/tf/tailfriend/facility/entity/ReviewPhoto.java, src/main/java/tf/tailfriend/facility/repository/ReviewDao.java, src/main/java/tf/tailfriend/facility/repository/ReviewPhotoDao.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java, src/main/resources/db/migration/V5__review_photos.sql
시설 상세보기 구현
-
-
-
-
Closes #이슈번호
=> [FIX] 시설 상세보기

src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
- 펫시터 목록을 조회할 때 현재 로그인한 사용자가 검색 결과에 포함되는거 삭제
=> [MODIFY] 임보구해요 수정

src/main/java/tf/tailfriend/file/service/FileService.java, src/main/java/tf/tailfriend/reserve/controller/ReserveController.java, src/main/java/tf/tailfriend/reserve/dto/ReserveDetailResponseDto.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java
=> 동영상 업로드 수정

src/main/java/tf/tailfriend/schedule/controller/CalendarReserveController.java, src/main/java/tf/tailfriend/schedule/entity/dto/CalendarReserveDTO.java
=> [FEAT] 캘린더 예약 연동

src/main/java/tf/tailfriend/facility/dto/FacilityResponseDto.java, src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/facility/repository/FacilityDao.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java, src/main/resources/db/migration/V5__alter_facility.sql
=> [FIX] 편의시설 테이블 컬럼 star_point -> total_star_point로 변경

src/main/java/tf/tailfriend/reserve/service/ReserveService.java
=> 끝나는시간 없을때 시작시간+1으로 추가

src/main/java/tf/tailfriend/facility/entity/dto/forReserve/FacilityWithDistanceProjection.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java
=> [FIX] 시설 리스트 수정

src/main/java/tf/tailfriend/petsitter/controller/PetSitterController.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java
=> [MODIFY] 펫시터 그만두기 상태 수정

src/main/java/tf/tailfriend/reserve/controller/PaymentController.java, src/main/java/tf/tailfriend/reserve/controller/ReserveController.java, src/main/java/tf/tailfriend/reserve/dto/PaymentHistoryDto.java, src/main/java/tf/tailfriend/reserve/repository/PaymentDao.java, src/main/java/tf/tailfriend/reserve/service/PaymentService.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java
=> [ADD]결제내역 구현

src/main/java/tf/tailfriend/admin/controller/AdminAnnounceController.java
=> [FEAT] 공지글 상세보기

src/main/java/tf/tailfriend/admin/controller/AdminAnnounceController.java, src/main/java/tf/tailfriend/admin/service/AnnounceService.java
=> [FEAT] 공지글 삭제

src/main/java/tf/tailfriend/chat/controller/ChatController.java, src/main/java/tf/tailfriend/notification/config/NotificationMessageConsumer.java, src/main/java/tf/tailfriend/notification/service/NotificationService.java
=> [MODIFY] 채팅방 입장했을때 상대방 메시지 받게 수정중

src/main/java/tf/tailfriend/notification/service/NotificationService.java
=> [MODIFY] 채팅방 생성은 프론트에서 알림안뜨게

src/main/java/tf/tailfriend/board/entity/Board.java, src/main/java/tf/tailfriend/board/repository/BoardBookmarkDao.java, src/main/java/tf/tailfriend/board/repository/BoardDao.java, src/main/java/tf/tailfriend/board/repository/BoardLikeDao.java, src/main/java/tf/tailfriend/board/repository/CommentDao.java, src/main/java/tf/tailfriend/board/repository/ProductDao.java, src/main/java/tf/tailfriend/chat/repository/ChatRoomDao.java, src/main/java/tf/tailfriend/chat/repository/TradeMatchDao.java, src/main/java/tf/tailfriend/pet/repository/PetDao.java, src/main/java/tf/tailfriend/pet/repository/PetMatchDao.java, src/main/java/tf/tailfriend/petsitter/entity/PetSitter.java, src/main/java/tf/tailfriend/petsitter/service/PetSitterService.java, src/main/java/tf/tailfriend/petsta/entity/PetstaComment.java, src/main/java/tf/tailfriend/petsta/entity/PetstaPost.java, src/main/java/tf/tailfriend/petsta/repository/PetstaBookmarkDao.java, src/main/java/tf/tailfriend/petsta/repository/PetstaCommentDao.java, src/main/java/tf/tailfriend/petsta/repository/PetstaLikeDao.java, src/main/java/tf/tailfriend/petsta/repository/PetstaPostDao.java, src/main/java/tf/tailfriend/petsta/service/PetstaPostService.java, src/main/java/tf/tailfriend/reserve/repository/PaymentDao.java, src/main/java/tf/tailfriend/reserve/repository/ReserveDao.java, src/main/java/tf/tailfriend/user/controller/UserController.java, src/main/java/tf/tailfriend/user/entity/User.java, src/main/java/tf/tailfriend/user/repository/UserFollowDao.java, src/main/java/tf/tailfriend/user/service/UserService.java
=> [FIX] 회원탈퇴 버그 수정 최종

src/main/java/tf/tailfriend/notification/repository/NotificationDao.java, src/main/java/tf/tailfriend/notification/service/NotificationService.java
=> [FIX] 방생성 알람은 미감지

src/main/java/tf/tailfriend/facility/service/FacilityService.java, src/main/java/tf/tailfriend/reserve/controller/ReserveController.java, src/main/java/tf/tailfriend/reserve/dto/RequestForFacility/ReviewInsertRequestDto.java, src/main/java/tf/tailfriend/reserve/dto/ReserveDetailResponseDto.java, src/main/java/tf/tailfriend/reserve/entity/Reserve.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java, src/main/resources/db/migration/V7__alter_reserves.sql
=> [FIX] 예약이 리뷰를 참조하도록 DB, 엔티티변경

src/main/java/tf/tailfriend/reserve/repository/ReserveDao.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java
=> [FIX] 예약 목록 최신순으로 반환

src/main/java/tf/tailfriend/reserve/controller/ReserveController.java
=> [FIX] 사진없이 리뷰 남길 수 있게 수정

src/main/resources/db/migration/V1__init_create_table.sql, src/main/resources/db/migration/V2__init_insert_data.sql, src/main/resources/db/migration/V3__alter_enum_distance.sql, src/main/resources/db/migration/V4__alter_comments.sql, src/main/resources/db/migration/V5__alter_facility.sql, src/main/resources/db/migration/V6__review_photos.sql, src/main/resources/db/migration/V7__alter_reserves.sql
=> [CHORE] flyway 초기화

src/main/java/tf/tailfriend/reserve/dto/PaymentHistoryDto.java, src/main/java/tf/tailfriend/reserve/repository/PaymentDao.java, src/main/java/tf/tailfriend/reserve/service/PaymentService.java
=> [FIX] 날짜값 결제일에서 체크인 날짜로 수정

src/main/java/tf/tailfriend/user/entity/dto/RegisterUserDto.java
=> [CHORE] 닉네임 8글자

src/main/java/tf/tailfriend/reserve/repository/PaymentDao.java, src/main/java/tf/tailfriend/reserve/service/PaymentService.java
=> [FIX] 결제일자 기준으로 필터링 원복

src/main/java/tf/tailfriend/facility/controller/FacilityController.java, src/main/java/tf/tailfriend/facility/entity/Facility.java, src/main/java/tf/tailfriend/facility/entity/Review.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java, src/main/java/tf/tailfriend/reserve/controller/ReserveController.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java
=> [FEAT] 리뷰 수정, 삭제 기능 구현 3차

src/main/java/tf/tailfriend/board/controller/BoardController.java, src/main/java/tf/tailfriend/board/dto/CommentResponseDto.java, src/main/java/tf/tailfriend/board/service/CommentService.java
=> [FIX] 댓글 공백으로 수정 오류 처리

src/main/java/tf/tailfriend/facility/service/FacilityService.java
=> [FIX] 예약 하나에 리뷰 한번만 가능

src/main/java/tf/tailfriend/admin/service/AnnounceService.java
=> [FIX] 버그 수정

src/main/java/tf/tailfriend/facility/entity/dto/forReserve/FacilityCardResponseDto.java, src/main/java/tf/tailfriend/facility/entity/dto/forReserve/FacilityWithDistanceProjection.java, src/main/java/tf/tailfriend/facility/repository/FacilityDao.java, src/main/java/tf/tailfriend/facility/service/FacilityService.java
=> [FIX] 시설 리스트 요청 응답 데이터에 tel 추가

src/main/java/tf/tailfriend/board/service/BoardService.java
=> [FIX] 중고게시판 가격 추가

src/main/java/tf/tailfriend/board/controller/BoardController.java, src/main/java/tf/tailfriend/board/service/BoardService.java
=> [FEAT] 거래 완료 기능 추가

src/main/java/tf/tailfriend/user/distance/Distance.java
=> [FIX] 거리 레벨에 따른 동 갯수 조정

src/main/java/tf/tailfriend/reserve/dto/PaymentHistoryDto.java, src/main/java/tf/tailfriend/reserve/dto/ReserveDetailResponseDto.java, src/main/java/tf/tailfriend/reserve/repository/PaymentDao.java, src/main/java/tf/tailfriend/reserve/service/PaymentService.java, src/main/java/tf/tailfriend/reserve/service/ReserveService.java
=> [FIX] 예약목록 진짜 마지막?
